version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - run:
                name: update-npm
                command: 'sudo npm install -g npm@6'
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                name: install-npm-wee
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ./node_modules
                    - run:
                        name: test
                        command: npm run test
                    - store_artifacts:
                        path: test-results.xml
                        prefix: tests
                    - store_artifacts:
                        path: coverage
                        prefix: coverage
                    - store_test_results:
                        path: test-results.xml
